export interface Vehicle {
  id: string;
  brand: 'Honda' | 'Peugeot' | 'Opel' | 'Suzuki' | 'Vespa' | 'Aprilia' | 'Segway';
  model: string;
  badge?: string;
  category: 'novo' | 'polovno' | 'moto' | 'atv';
  bodyType: 'SUV' | 'Hečbek' | 'Sedan' | 'Krosover' | 'Motor' | 'Skuter' | 'ATV / Kvad';
  year: number;
  priceEur: number;
  monthlyEstimateEur: number;
  mileageKm: number;
  fuel: 'e:HEV Hibrid' | 'Plug-in Hibrid' | 'Benzin' | 'Dizel' | 'Električni';
  transmission: 'e-CVT Automatik' | '8-stepeni Automatik' | 'Manuelni 6 brzina' | 'CVT Automatik';
  powerHp: number;
  engineCc: number;
  has3D?: boolean;
  model3DId?: 'civic' | 'crv';
  image: string;
  gallery: string[];
  tags: string[];
  highlight: string;
  specs: {
    acceleration: string;
    topSpeed: string;
    consumption: string;
    trunk: string;
    warranty: string;
  };
}

export const INVENTORY_VEHICLES: Vehicle[] = [
  {
    id: 'honda-civic-rs',
    brand: 'Honda',
    model: 'Civic 2.0 e:HEV RS',
    badge: 'Sport Edition · 3D Dostupno',
    category: 'novo',
    bodyType: 'Hečbek',
    year: 2026,
    priceEur: 38990,
    monthlyEstimateEur: 345,
    mileageKm: 0,
    fuel: 'e:HEV Hibrid',
    transmission: 'e-CVT Automatik',
    powerHp: 184,
    engineCc: 1993,
    has3D: true,
    model3DId: 'civic',
    image: '/images/unnamed (1).webp',
    gallery: [
      '/images/unnamed (1).webp',
      '/images/unnamed (2).webp',
      '/images/unnamed (3).webp',
    ],
    tags: ['Hibrid', 'Sport', 'Novo', 'Honda Sensing', 'Bose Sound'],
    highlight: 'Kombinacija izuzetne sportske dinamike i hibridne efikasnosti sa 184 KS i 315 Nm.',
    specs: {
      acceleration: '7.8 s (0-100 km/h)',
      topSpeed: '180 km/h',
      consumption: '4.7 l / 100 km',
      trunk: '410 litara',
      warranty: '5 godina ili 100.000 km',
    },
  },
  {
    id: 'honda-crv-2026',
    brand: 'Honda',
    model: 'CR-V 2.0 e:PHEV Advance Tech',
    badge: 'Flagship SUV · 3D Dostupno',
    category: 'novo',
    bodyType: 'SUV',
    year: 2026,
    priceEur: 52990,
    monthlyEstimateEur: 480,
    mileageKm: 0,
    fuel: 'Plug-in Hibrid',
    transmission: 'e-CVT Automatik',
    powerHp: 215,
    engineCc: 1993,
    has3D: true,
    model3DId: 'crv',
    image: '/images/unnamed (4).webp',
    gallery: [
      '/images/unnamed (4).webp',
      '/images/unnamed (5).webp',
      '/images/unnamed (6).webp',
    ],
    tags: ['PHEV', 'SUV', 'AWD', 'Panorama', 'Masažna sedišta'],
    highlight: 'Do 82 km čiste električne autonomije u gradu, uz vrhunski nivo komfora i prostranosti.',
    specs: {
      acceleration: '9.0 s (0-100 km/h)',
      topSpeed: '195 km/h',
      consumption: '0.8 l / 100 km (kombinovano)',
      trunk: '617 litara',
      warranty: '8 godina na bateriju',
    },
  },
  {
    id: 'peugeot-3008-gt',
    brand: 'Peugeot',
    model: '3008 GT Hybrid 136 e-DCS6',
    badge: 'Novi Fastback SUV',
    category: 'novo',
    bodyType: 'SUV',
    year: 2025,
    priceEur: 36490,
    monthlyEstimateEur: 320,
    mileageKm: 0,
    fuel: 'e:HEV Hibrid',
    transmission: '8-stepeni Automatik',
    powerHp: 136,
    engineCc: 1199,
    image: '/images/unnamed (7).webp',
    gallery: [
      '/images/unnamed (7).webp',
      '/images/unnamed (8).webp',
    ],
    tags: ['Novi Model', 'Panoramic i-Cockpit', 'Focal Audio'],
    highlight: 'Revolucionarni Panoramic i-Cockpit od 21 inča sa zakrivljenim ekranom visoke rezolucije.',
    specs: {
      acceleration: '10.2 s (0-100 km/h)',
      topSpeed: '201 km/h',
      consumption: '5.5 l / 100 km',
      trunk: '520 litara',
      warranty: '5 godina garancije',
    },
  },
  {
    id: 'opel-astra-gs',
    brand: 'Opel',
    model: 'Astra GS Line 1.2 Turbo',
    badge: 'Nemački Inženjering',
    category: 'novo',
    bodyType: 'Hečbek',
    year: 2025,
    priceEur: 27900,
    monthlyEstimateEur: 245,
    mileageKm: 0,
    fuel: 'Benzin',
    transmission: '8-stepeni Automatik',
    powerHp: 130,
    engineCc: 1199,
    image: '/images/unnamed (9).webp',
    gallery: ['/images/unnamed (9).webp'],
    tags: ['Intelli-Lux LED', 'AGR sedišta', 'Head-up Display'],
    highlight: 'Nagrađivana Intelli-Lux Pixel LED svetla sa 168 individualnih LED elemenata.',
    specs: {
      acceleration: '9.7 s (0-100 km/h)',
      topSpeed: '210 km/h',
      consumption: '5.6 l / 100 km',
      trunk: '422 litara',
      warranty: '4 godine garancije',
    },
  },
  {
    id: 'honda-hrv-advance',
    brand: 'Honda',
    model: 'HR-V 1.5 e:HEV Advance Style',
    badge: 'Urbani Krosover',
    category: 'novo',
    bodyType: 'Krosover',
    year: 2025,
    priceEur: 33490,
    monthlyEstimateEur: 295,
    mileageKm: 0,
    fuel: 'e:HEV Hibrid',
    transmission: 'e-CVT Automatik',
    powerHp: 131,
    engineCc: 1498,
    image: '/images/unnamed.webp',
    gallery: ['/images/unnamed.webp'],
    tags: ['Magic Seats', 'Samopuneći Hibrid', 'Dvobojna Karoserija'],
    highlight: 'Poznata Honda Magic Seats magična sedišta koja se podižu kao u bioskopu.',
    specs: {
      acceleration: '10.6 s (0-100 km/h)',
      topSpeed: '170 km/h',
      consumption: '5.4 l / 100 km',
      trunk: '335 - 1305 litara',
      warranty: '5 godina / 100.000 km',
    },
  },
  {
    id: 'suzuki-vitara-hybrid',
    brand: 'Suzuki',
    model: 'Vitara 1.4 BoosterJet AllGrip Premium',
    badge: '4x4 Pogon',
    category: 'novo',
    bodyType: 'SUV',
    year: 2025,
    priceEur: 24900,
    monthlyEstimateEur: 215,
    mileageKm: 0,
    fuel: 'e:HEV Hibrid',
    transmission: 'Manuelni 6 brzina',
    powerHp: 129,
    engineCc: 1373,
    image: '/images/unnamed (2).webp',
    gallery: ['/images/unnamed (2).webp'],
    tags: ['AllGrip 4WD', 'Japanska Pouzdanost', 'Kamera 360'],
    highlight: 'Dokazani AllGrip pogon na sva 4 točka sa 4 režima vožnje (Auto, Sport, Snow, Lock).',
    specs: {
      acceleration: '10.2 s (0-100 km/h)',
      topSpeed: '190 km/h',
      consumption: '5.8 l / 100 km',
      trunk: '375 litara',
      warranty: '3 godine + 7 godina produženo',
    },
  },
  {
    id: 'certified-peugeot-2008-gt',
    brand: 'Peugeot',
    model: '2008 GT 1.5 BlueHDi Automatic',
    badge: 'Sertifikovano Polovno · 1. Vlasnik',
    category: 'polovno',
    bodyType: 'Krosover',
    year: 2022,
    priceEur: 21490,
    monthlyEstimateEur: 185,
    mileageKm: 48500,
    fuel: 'Dizel',
    transmission: '8-stepeni Automatik',
    powerHp: 130,
    engineCc: 1499,
    image: '/images/unnamed (3).webp',
    gallery: ['/images/unnamed (3).webp'],
    tags: ['Kupljen nov u Srbiji', 'Kompletna Servisna Istorija', '12 Meseci Garancije'],
    highlight: 'Vozilo kupljeno i održavano u ovlašćenom Car Box servisu, provereno u 110 tačaka.',
    specs: {
      acceleration: '9.3 s (0-100 km/h)',
      topSpeed: '195 km/h',
      consumption: '4.8 l / 100 km',
      trunk: '434 litara',
      warranty: '12 meseci pisana garancija',
    },
  },
  {
    id: 'vespa-gts-300-super',
    brand: 'Vespa',
    model: 'GTS 300 Super Sport HPE',
    badge: 'Ikona Stila · Moto Program',
    category: 'moto',
    bodyType: 'Skuter',
    year: 2025,
    priceEur: 7490,
    monthlyEstimateEur: 75,
    mileageKm: 0,
    fuel: 'Benzin',
    transmission: 'CVT Automatik',
    powerHp: 24,
    engineCc: 278,
    image: '/images/unnamed (5).webp',
    gallery: ['/images/unnamed (5).webp'],
    tags: ['HPE Agregat', 'Keyless', 'TFT Display', 'ABS/ASR'],
    highlight: 'Najsnažniji motor u istoriji Vespe sa preko 23.8 KS i najsavremenijim Keyless sistemom.',
    specs: {
      acceleration: 'Brz start na semaforu',
      topSpeed: '125 km/h',
      consumption: '3.3 l / 100 km',
      trunk: 'Kaciga pod sedištem',
      warranty: '2 godine bez limita km',
    },
  },
  {
    id: 'segway-snarler-600',
    brand: 'Segway',
    model: 'Snarler AT6 L Limited EPS',
    badge: 'Off-Road Zver · ATV Program',
    category: 'atv',
    bodyType: 'ATV / Kvad',
    year: 2025,
    priceEur: 8990,
    monthlyEstimateEur: 90,
    mileageKm: 0,
    fuel: 'Benzin',
    transmission: 'CVT Automatik',
    powerHp: 44,
    engineCc: 570,
    image: '/images/unnamed (6).webp',
    gallery: ['/images/unnamed (6).webp'],
    tags: ['4x4 Blokada', 'Vitlo 2.500 lbs', 'Smart Commanding App'],
    highlight: 'Smart Commanding aplikacija sa GPS praćenjem, SOS alarmom i telemetrijom u realnom vremenu.',
    specs: {
      acceleration: 'Visok obrtni moment 48 Nm',
      topSpeed: '105 km/h',
      consumption: 'Ekonomičan DOHC',
      trunk: 'Prednji & zadnji nosač',
      warranty: '2 godine fabričke garancije',
    },
  },
];
